# Site settings
title: 水上书
header-img: "img/home icon1.jpg"
tagline: "cn"  
description: "一切都会像水消失在水中，而文字会留下涟漪"  
baseurl: ""
url: "http://whozj.me"  

# About/contact
owner: 
  name: "WhoZJ"
  email: luoge31819@hotmail.com
  bio: "一个独立内敛的人，好奇心，念旧者"

# Data
gavatar: img/favicon.png
favicon: img/favicon.ico

douban_username:  
twitter_username: huyiren0407
github_username: whozj
facebook_username: 
instagram_username: whozj
zhihu_username: huyiren

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "WhoZJ"
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : disqus
  disqus :
      short_name : whozj

# Analytics and webmaster tools stuff goes here
google_analytics: UA-111669368-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation